# -*- coding: utf-8 -*-
"""Accuracy_of_ML_Algo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgyCjmLQluO57XH3GJ9-1fyYbRp5puVR
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier

data = pd.read_excel("Iris_train.xlsx")

x = data.iloc[:,:-1]  #selecting all rows and all columns excpet the last as it is the label

#printing y i.e labels
y = data.iloc[:,-1]   #all rows but only last column

#training the model
model = RandomForestClassifier()
model.fit(x.values,y.values)

predictions = model.predict([[6.2,2.8,4.8,1.8]])
predictions

test_data = pd.read_excel("Iris_test.xlsx")

x_test = test_data.iloc[:,:-1]

test_result = model.predict(x_test.values)
test_result

y_test = test_data.iloc[:,-1]
y_test.values

"""### Accuracy tells us how often the model was right"""

actual = y_test.values

count = 0
for i in range(0,len(actual)):
    if actual[i] == test_result[i]:
        count +=1
accuracy = (count*100)/len(actual)
print(f"The accuracy of the above model is {accuracy}!")